install.packages("remotes")
library(remotes)
 options(repos = c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/testing"))
install_version("INLA", "24.12.11")
install_version("geoR", "1.9-4")
install_version("dlnm", "2.4.7")
install_version("reshape2", "1.4.4")
install_version("MASS", "7.3-64")
install_version("readxl", "1.4.5")
install_version("tidyverse", "2.0.0")
install_version("sf", "1.0-19")
install_version("viridis", "0.6.5")
install_version("gridExtra", "2.3")
install_version("PrevMap", "1.5.3") 
